version: "3.5"

services:

  ckan:
    image: ndslabs/ckan
    env_file: ./ckan.env
    networks:
      - ckan
    depends_on:
      - solr
      - postgres
      - redis
    links:
      - postgres:db
      - redis:redis
      - solr:solr
    ports:
      - 5000:5000
    volumes:
      - ckan:/var/lib/ckan
    restart: unless-stopped

  solr:
    image: ckan/solr:release-v2.5.3
    env_file: ./solr.env
    networks:
      - ckan
    depends_on:
      - postgres
      - redis
    links:
      - postgres:db
      - redis:redis
    ports:
      - 8983:8983
    volumes:
      - solr:/opt/solr/server/solr/ckan/data
    restart: unless-stopped

  redis:
    image: redis:3.0
    networks:
      - ckan
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped

  postgres:
    image: postgres:9.3
    env_file: ./postgres.env
    networks:
      - ckan
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  ckan:


volumes:
  ckan:
  solr:
  redis:
  postgres:
